### PR TITLE
Main code

### PR DESCRIPTION
**Pull request by phalado**

### CODE REVIEW

**Review by ebukaume — CHANGES_REQUESTED** [review]
## Changes Required! :stop_sign: 

Hi @phalado :wave: 

You work goods really good, however, let's fix these issues.

- [x] You need to add a README and it has to be descriptive. You can check [this repo](https://github.com/othneildrew/Best-README-Template) out if you need some inspiration.

- [x] You are using the wrong `stickler configuration`. Please refer to [this repo](https://github.com/microverseinc/linters-config/tree/master/css) for instructions. You are required to use the provided configuration.

- [x] No `!important` overusing. Kindly refer to [this article](https://speckyboy.com/good-bad-css-practices) for more information on why this is a very bad idea.
review-bootstrap-important


- [x] Your main nav links are squashed together at the medium breakpoint. Please fix it. 
review-bootstrap-nav-links

- [x] Finally, make your page take full width at the small breakpoint.
review-bootstrap-margin

**Please submit another code review request after fixing those**

Happy Coding :v: 
**Ebuka Umeokonkwo**
 [Github](https://github.com/ebukaume) | [Linkedin](https://www.linkedin.com/in/ebukaume) | [Slack](https://app.slack.com/team/UFDKXE68L) | [Twitter](https://twitter.com/ebukaume)

**Comment by phalado** [comment]
> ## Changes Required! 🛑
> Hi @phalado 👋
> 
> You work goods really good, however, let's fix these issues.
> 
> * [x]  You need to add a README and it has to be descriptive. You can check [this repo](https://github.com/othneildrew/Best-README-Template) out if you need some inspiration.
> * [x]  You are using the wrong `stickler configuration`. Please refer to [this repo](https://github.com/microverseinc/linters-config/tree/master/css) for instructions. You are required to use the provided configuration.
> * [x]  No `!important` overusing. Kindly refer to [this article](https://speckyboy.com/good-bad-css-practices) for more information on why this is a very bad idea.
>   review-bootstrap-important
> * [x]  Your main nav links are squashed together at the medium breakpoint. Please fix it.
>   review-bootstrap-nav-links
> * [x]  Finally, make your page take full width at the small breakpoint.
>   review-bootstrap-margin
> 
> **Please submit another code review request after fixing those**
> 
> Happy Coding ✌️
> **Ebuka Umeokonkwo**
> [Github](https://github.com/ebukaume) | [Linkedin](https://www.linkedin.com/in/ebukaume) | [Slack](https://app.slack.com/team/UFDKXE68L) | [Twitter](https://twitter.com/ebukaume)

So... I corrected everything asked. 

About the `!important` I was really overusing. I killed more than 40 of then, but I needed some, so the ones that survived are really necessary.

Thx for the review. I will ask another in the Dashboard.

**Review by Redvanisation — CHANGES_REQUESTED** [review]
# Changes required  🛑

### Hello @phalado   🌟

**Good work on this project, but we need to fix the issues below before moving on ⬇️** 

- The navbar isn't responsive on small and medium screen sizes, please fix that.
Screen Shot 2019-11-08 at 10 13 23 PM

### _After making the required changes please submit a new code review request_

### Good luck! 🍀

**Comment by shshamim63** [comment]
## Status :arrow_right:  [Approved!] :arrow_right:
___
Hi @phalado :wave: ,
Well done :clap: . code looks neat and clean. But there are enough space to decorate the readme, I think. Rest are absolutely fine.
___
#### This :+1: is from me. You can merge it now. and don't forget to fill the project completion form.
___
## :clubs: Happy Coding :clubs: 
### Shakhawat Hossain
[Linkedin](https://www.linkedin.com/in/shakhawat-hossain-7750b0127/)| [Slack](Shakhawat Hossain)

**Pull request merged**
